#!/bin/zsh
# Z-Shell aliases

# Aliases for XDG-compliant config files

alias wget="wget --hsts-file=$XDG_CACHE_HOME/wget-hsts --no-config"
alias mbsync="mbsync -c $XDG_CONFIG_HOME/isync/mbsyncrc --all"
alias neomutt="neomutt -F $XDG_CONFIG_HOME/mutt/muttrc"
alias lf="$XDG_CONFIG_HOME/lf/lfub"

# Abbreviations

alias cddev="cd $DEVEL_DIR"
alias scim="sc-im"
alias ap="absolutely-proprietary -f"
alias za="zathura"
alias trc="tremc"
alias mc="minecraft"

# Overrides
alias sudo="doas"
alias diff="diff --color --suppress-common-lines -y"
alias shutdown="doas /usr/bin/shutdown -h now"
alias reboot="doas /usr/bin/reboot"
alias mount="doas /usr/bin/mount"
alias umount="doas /usr/bin/umount"
alias rstudio="rstudio-bin --no-sandbox"
alias history="history 1"
alias ls="ls --color"
alias grep="grep --color"
alias scli="scli -nfs --color=high"
