#!/bin/sh
#
# A script for copying emojis using dmenu

source "$HOME/scripts/res/loadres"
RESOURCE="emoji.txt"
EMOJILIST="$SCRIPT_RES/$RES_SUBDIR/$RESOURCE"

grep -v "#" "$EMOJILIST" | dmenu -l 15 -g 1 -sb "#9544FF" | awk '{print $1}' | tr -d '\n' | xclip -selection clipboard
[ -n "$(xclip -o -selection clipboard)" ] && \
notify-send "Emoji Copy" "$(xclip -o -selection clipboard) copied to clipboard"
