#!/bin/sh
#
# Helper script for connecting printers
# TODO: Fix eval command

source "$HOME/scripts/res/loadres"
CACHE="printers"
CACHE_PATH="$SCRIPT_RES/$RES_SUBDIR/$CACHE"

if [ -f "$CACHE_PATH" ]
then
   PNAME=$(cat "$CACHE_PATH" | dmenu -p "Printers" -l 15 \
   -g 1 -nb "#222222" -nf "#bbbbbb" -sb "#005577" -sf "#eeeeee")
else
   while
      echo "Enter IP address (xxx.xxx.xxx.xxx): " && read -r IP
      echo "$IP" | grep -P "(\d{3})((\.\d{3}){3})" > /dev/null
      (("$?" != "0"))
   do :; done
   echo "Enter printer's name: " && read -r PNAME
   echo "$PNAME $IP" > "$CACHE_PATH"
fi

CMD="lpadmin -p $PNAME -E -v ipp://$IP/ipp/print -m everywhere"
echo "$CMD"
eval "$CMD"
