#!/bin/sh
#
# Description: Take a screenshot of the current window
# Dependencies: notify-send

set -- ./capture?.jpg

i=1
[ "$1" = "./capture?.jpg" ] || for _ in "$@"; do
    i=$((i + 1))
done

OUT_FILE="capture${i}.jpg"
import -window root "$OUT_FILE" && \
notify-send "Capture 📷" "Captured screenshot $OUT_FILE"
