#!/bin/sh
#
# Purpose: Generate a README file skeleton for personal projects
#
# Dependencies: figlet

README_SKEL="$SCRIPT_DIR/res/$(basename "$0")/README_SKEL.md"

# Get the name of the root directory
ROOT_NAME="${PWD#"$DEVEL_DIR"/}"
ROOT_NAME="$(echo "$ROOT_NAME" | cut -d '/' -f1)"
# Get the absolute path to the root directory
PROJECT_ROOT="$(pwd | sed "s/\($ROOT_NAME\).*/\1/")"

if [ -f "$PROJECT_ROOT"/README.md ]
then
   printf "README.md already exists in project root. Overwrite? [y/n] "; read -r ANS
   [ "$ANS" != "y" ] && \
   [ "$ANS" != "Y" ] && \
   [ "$ANS" != "yes" ] && \
   [ "$ANS" != "YES" ] && \
   [ "$ANS" != "Yes" ] && echo "Exiting..." && exit 0
fi

# Use figlet to output banner name into README.md
BANNER="$(figlet -lp "$(echo "$ROOT_NAME" | sed 's/_//g')")"
printf "%s\n" "<pre>" > "$PROJECT_ROOT"/README.md
printf "%s\n" "$BANNER" >> "$PROJECT_ROOT"/README.md
printf "%s\n\n" "</pre>" >> "$PROJECT_ROOT"/README.md

cat "$README_SKEL" >> "$PROJECT_ROOT"/README.md
