#!/bin/sh
# 
# Used as an alias for lualatex so that all files except pdf are moved
# 
# Dependencies: lualatex, tex-live

PDF_NAME="$(echo "$1" | sed 's/\.tex/\.pdf/g')"
lualatex --shell-escape --output-directory="$XDG_DATA_HOME/latex/output" "$1" && \
mv "$XDG_DATA_HOME/latex/output/$PDF_NAME" "$PWD"
