#!/bin/sh
#
# Description: Generate a README file skeleton for personal projects
# Dependencies: figlet

README_SKEL="$SCRIPT_DIR/res/$(basename "$0")/README_SKEL.md"
PROJ_DIR="$(basename "$PWD")"

if [ -f "README.md" ]; then
    while
        printf "README.md already exists in project root. Overwrite? [y/n] "; read -r INPUT
        INPUT="$(echo "$INPUT" | tr '[:upper:]' '[:lower:]')"
        [ "$INPUT" != "y" ] && \
        [ "$INPUT" != "yes" ] && \
        [ "$INPUT" != "n" ] && \
        [ "$INPUT" != "no" ]
    do :; done
fi

[ "$INPUT" = "n" ] || [ "$INPUT" = "no" ] && echo "Exiting..." && exit 0

# Use figlet to output banner name into README.md
PROJ_NAME="$(echo "$PROJ_DIR" | sed 's/_/ /g')"
BANNER="$(figlet -lp "$PROJ_NAME" | sed '/^\s*$/d')"
printf "%s\n%s\n%s\n\n" "\`\`\`" "$BANNER" "\`\`\`" > "README.md"

cat "$README_SKEL" >> "README.md"
