#!/bin/sh
#
# Purpose: Helper script for connecting printers
# Dependencies: lpadmin, dmenu

CACHE_FILE="$XDG_CACHE_HOME/$(basename "$0")"
IP_REGEX="(\d{1,3})((\.\d{1,3}){3})"

add_new() {
    while
        printf "Enter IP address (xxx.xxx.xxx.xxx): "; read -r IP
        [ "$(echo "$IP" | grep -P "$IP_REGEX")" = "" ]
    do :; done

    while
        printf "Enter printer's name: "; read -r PNAME
        [ "$PNAME" = "" ]
    do :; done

    ! [ -f "$CACHE_FILE" ] || \
        [ "$(grep -x "$PNAME $IP" "$CACHE_FILE")" = "" ] && \
        echo "$PNAME $IP" >> "$CACHE_FILE"
}

# TODO: sel_existing() does not validate case where user exits dmenu via ESC
sel_existing() {
   SELECTION="$(dmenu -p "Printers" -l 15 < "$CACHE_FILE")"
   PNAME="$(echo "$SELECTION" | awk '{print $1}')"
   IP="$(echo "$SELECTION" | awk '{print $2}')"
}

del_cache() {
    while
        printf "Are you sure you'd like to delete the printer cache? [y/n] "; read -r INPUT
        INPUT="$(echo "$INPUT" | tr '[:upper:]' '[:lower:]')"
        [ "$INPUT" != "y" ] && \
        [ "$INPUT" != "yes" ] && \
        [ "$INPUT" != "n" ] && \
        [ "$INPUT" != "no" ]
    do :; done
    [ "$INPUT" = "y" ] || [ "$INPUT" = "yes" ] && rm "$CACHE_FILE" && exit 0
    menu
}

menu() {
    if [ -f "$CACHE_FILE" ]; then
        while
            printf "%s\n%s\n%s\n%s\n" \
                "1) Create new printer" \
                "2) Use existing printer" \
                "3) Clear printer cache" \
                "4) Exit"; read -r INPUT

            [ "$INPUT" != "1" ] && \
            [ "$INPUT" != "2" ] && \
            [ "$INPUT" != "3" ] && \
            [ "$INPUT" != "4" ]
        do :; done

        case "$INPUT" in
            "1")
                add_new
                ;;
            "2")
                sel_existing
                ;;
            "3")
                del_cache
                ;;
            "4")
                exit 0
        esac
    else
        add_new
    fi
}

# Script start

menu

CMD="lpadmin -p $PNAME -E -v ipp://$IP/ipp/print -m everywhere"
echo "$CMD"
eval "$CMD"
