" PATH VARIABLES

set runtimepath^=$XDG_CONFIG_HOME/vim
set packpath^=$XDG_CONFIG_HOME/vim/plugged

" CONFIG START

syntax on
let mapleader=" "

" PLUGGINS

call plug#begin('~/.config/vim/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'vim-airline/vim-airline'
Plug 'altercation/vim-colors-solarized'
call plug#end()

" SETS

set encoding=utf-8
set splitbelow splitright
set number relativenumber
set smartindent
set expandtab
set tabstop=3
set softtabstop=3
set shiftwidth=3
set scrolloff=8
set smartcase
set nohlsearch
set incsearch
set noswapfile
set nobackup
set undodir=~/.config/vim/undodir
set undofile
set wildmode=longest,list,full

" MAPPINGS

map <leader>c :set signcolumn=yes <CR>
map <leader>C :set signcolumn=no <CR>
map <leader>s :!clear && shellcheck %<CR>
map <leader>so :so %<CR>
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l
nnoremap <Up> 5<C-w><S-+>
nnoremap <Down> 5<C-w><S-->
nnoremap <Left> 10<C-w><S->>
nnoremap <Right> 10<C-w><S-<>

" AUTO COMMANDS

" Detect latex files properly
autocmd BufRead,BufNewFile *.tex set filetype=tex

" Set spellcheck on for tex, latex, markdown
autocmd FileType tex,latex,markdown setlocal spell! spelllang=en_us

" Center page on transition to insert mode
autocmd InsertEnter * norm zz

" Clear trailing whitespace on save
autocmd BufWritePre * %s/\s\+$//e
