" PATH VARIABLES

set runtimepath^=$XDG_CONFIG_HOME/vim
set packpath^=$XDG_CONFIG_HOME/vim/plugged
set viminfo=%,<800,'10,/50,:100,h,f0,n~/.config/vim/viminfo

" CONFIG START

syntax on
let mapleader=" "
" Use degraded 256 colorscheme
let g:solarized_termcolors=256

" PLUGGINS

source $XDG_CONFIG_HOME/vim/cscope.vim

call plug#begin('~/.config/vim/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'vim-airline/vim-airline'
Plug 'altercation/vim-colors-solarized'
call plug#end()

" SETS

set background=dark
set encoding=utf-8
set pastetoggle=<F12>
set clipboard=unnamedplus
set splitbelow splitright                    " Window split directions
set number relativenumber
set smartindent
set expandtab
set tabstop=3
set softtabstop=3
set shiftwidth=3
set scrolloff=8                              " # of lines between cursor before screen scrolls
set ignorecase
set smartcase
set nohlsearch                               " GOTO words as the pattern is being typed
set incsearch
set noswapfile
set nobackup
set undodir=~/.config/vim/undodir
set undofile
set wildmode=longest,list,full
set signcolumn=no                            " Turn signcolumn off by default for Git-Gutter
set updatetime=100                           " Realtime update delay for Git-Gutter
" Pressing ESC into norm mode followed by Shift+o stalls
" The fix is to set ttimeoutlen to something small
set timeout ttimeout
set timeoutlen=500
set ttimeoutlen=20

" MAPPINGS

nnoremap <leader>c :set signcolumn=yes <CR>
nnoremap <leader>C :set signcolumn=no <CR>
nnoremap <leader>s :!clear && shellcheck %<CR>
nnoremap <leader>so :so %<CR>
" Toggle smartcase
nnoremap <leader>/ :set smartcase!<CR>:set smartcase?<CR> " Toggle smartcase

" Switching windows
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Copy and paste (in visual mode)
vnoremap <A-c> "+y
vnoremap <A-x> "+c
vnoremap <A-v> "+p
inoremap <A-v> <ESC>"+p

" Resizing windows
nnoremap <Up> 5<C-w><S-+>
nnoremap <Down> 5<C-w><S-->
nnoremap <Left> 10<C-w><S->>
nnoremap <Right> 10<C-w><S-<>

" Center page on word search or Ctrl + d/u
nnoremap n nzz
nnoremap N Nzz
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz

" AUTO COMMANDS

" Detect latex files properly
autocmd BufRead,BufNewFile *.tex set filetype=tex

" Set spellcheck on for tex, latex, markdown
" autocmd FileType tex,latex,markdown setlocal spell! spelllang=en_us

" Center page on transition to insert mode
autocmd InsertEnter * norm zz

" Clear trailing whitespace on save
autocmd BufWritePre * %s/\s\+$//e

" OTHER

colorscheme solarized
