#!/bin/sh

STATE=
case "$MPD_PLAYER_STATE" in
   "play")
      STATE="Playing:"
      ;;
   "pause")
      STATE="Pausing:"
      ;;
   "stop")
      STATE="Stopping:"
      ;;
   *)
      exit 0
      ;;
esac
notify-send "ncmpcpp:" "$STATE $(mpc -f "%title%" | sed 1q)"
