#!/bin/sh
#
# Purpose: Connect headphones to bluetooth
#
# Dependencies: bluetoothctl, bluez5
#
# If you consistently have troubles connecting, even after using bt off, you will
# need to restart your audio daemon, enter bluetoothctl manually, remove device,
# power off, scan off, and reset device list on headphones. Then try again

SELECTION=$1
MAC=28:11:A5:44:BE:B0

signal_handler() {
   echo
   PAIR_STAT=$(bluetoothctl info $MAC | sed '9q;d' | awk '{print $2}')
   [ "$PAIR_STAT" = "yes" ] && echo "Successfully paired with $MAC!" || echo "Failed to pair with $MAC..."
   kill -TERM -$$
}

turnon() {
   trap signal_handler INT

	echo "Please put headphones in pairing mode. Wait a second or two and then press Ctrl+C to pair."
   echo "If this fails, turn headphones off and try again."
	bluetoothctl power on
	bluetoothctl scan on
	bluetoothctl connect $MAC

   for i in {1..100}
   do
      sleep 1 &
   done

   wait
}

turnoff() {
	bluetoothctl disconnect $MAC
	bluetoothctl power off
	bluetoothctl quit
	echo "Disconnected from $MAC"
}

case $SELECTION in
on)
   turnon
   ;;
off)
   turnoff
   ;;
*)
   echo "Options:"
   echo
   echo "    on) Attempts to connect with headphones. Headphones must be in pairing mode."
   echo "    off) Terminates connection between headphones and bluetooth dongle."
   echo
	;;
esac
