#!/bin/sh
#
# Purpose: Connect bluetooth headphones
#
# Dependencies: bluetoothctl, bluez5
#
# If you consistently have troubles connecting, even after using bt off, you will
# need to restart your audio manager, enter bluetoothctl manually, remove device,
# power off, scan off, and reset device list on headphones.
#
# If you recieve error "Could not find default agent", try removing bluetooth dongle
# from USB port and plug back in.

SELECTION=$1
MAC=28:11:A5:44:BE:B0

signal_handler() {
   echo
   PAIR_STAT=$(bluetoothctl info $MAC | sed '9q;d' | awk '{print $2}')
   [ "$PAIR_STAT" = "yes" ] && echo "Successfully paired with $MAC!" || echo "Failed to pair with $MAC..."
   kill -TERM -$$
}

turnon() {
   trap signal_handler INT

	echo "Please run this script before turning headphones on."
   echo "Wait a moment until headphones are connected and press Ctrl+C once paired."
	bluetoothctl power on
	bluetoothctl scan on
	bluetoothctl connect $MAC

   for i in {1..100}
   do
      sleep 1 &
   done

   wait
}

turnoff() {
	bluetoothctl disconnect $MAC
	bluetoothctl power off
	bluetoothctl quit
	echo "Disconnected from $MAC"
}

case $SELECTION in
on)
   turnon
   ;;
off)
   turnoff
   ;;
*)
   echo "Options:"
   echo
   echo "    on) Attempts to connect with headphones."
   echo "    off) Terminates connection between headphones and bluetooth dongle."
   echo
	;;
esac
