#!/bin/sh
# Take a screenshot of the entire window

EXISTING=$(ls capture?.png)

i=0
for FILE in $EXISTING; do
   i=$((i+1))
done

OUT_FILE=capture$i.png
import -window root $OUT_FILE
notify-send "Captured screenshot $OUT_FILE"
