#!/bin/sh
#
# Configure my stupid HP DeskJet printer
# TODO: Fix eval command

echo_and_run()
{
   echo "$1"
   #eval "$(printf '%q ' "$@")" < /dev/tty
   eval "$(printf '%s\n' "$1" | sed "s/'/'\\\\''/g; 1 s/^/'/; $ s/$/'/")" < /dev/tty
}

echo "Enter IP address: " && read -r IP
CMD="lpadmin -p HP_DeskJet_Plus_4152 -E -v ipp://$IP/ipp/print -m everywhere"
echo_and_run "$CMD"
