#!/bin/sh
#
# Pull all repositories from git

GIT_DIR=$HOME/devel/github
DOC_DIR=$HOME/docs
API=https://api.github.com/users/NeilKingdom/repos

cd $GIT_DIR
# Optionally uncomment if Misc directory should not be pulled
#ls -l | grep -v Misc | xargs rm -rf
ls -l | xargs rm -rf
curl $API -o $GIT_DIR/.meta

# Cant output directly to .meta because it's being operated on
grep '"name"' .meta | sed -r 's/name|[",:]//g' > .temp
cat .temp > .meta && rm .temp

# Clone all repositories
while read -r LINE; do
	git clone "https://github.com/NeilKingdom/$LINE.git"
done < .meta

# Optionally move notes to ~/docs
# NOTE: mv clobbers existing directories by default
mv CET_Notes $DOC_DIR
mv Mathematics_Notes $DOC_DIR
