#!/bin/sh

# Auto setup for qemu

ISO_PATH=$HOME/devel/VMs/isos

SELECT=$(echo $(ls $ISO_PATH) | tr " " "\n" | sort | dmenu -i -l 10 -p "Enter the desired ISO")
echo "Selected $SELECT"
qemu-system-x86_64 \
-boot order=d \
-cdrom $ISO_PATH/$SELECT \
# TODO: Dynamically create boot image
-hda linux.img \ 
-m 3G \
--enable-kvm \
-machine smm=off \
-usb -device usb-kbd
