#!/bin/sh
#
# Description: Send a push notification when the state of MPD has changed
# Dependencies: notify-send, mpd, mpc

case "$MPD_PLAYER_STATE" in
    "play")
        STATE="Playing:"
        ;;
    "pause")
        STATE="Pausing:"
        ;;
    "stop")
        STATE="Stopping:"
        ;;
    *)
        exit 0
        ;;
esac

notify-send "ncmpcpp:" "$STATE $(mpc -f "%title%" | sed 1q)"
