#!/bin/sh
#
# Description: Mimeapp script for adding torrent to transmission-daemon, but will also start
# the daemon first if not running
# Dependencies: notify-send, transmission

if [ -n "$(pgrep transmission-daemon)" ]; then
    notify-send "Starting transmission daemon..."
    transmission-daemon &
fi

transmission-remote -a "$@" && notify-send "Transmission-daemon" "Torrent added."
