#!/bin/sh
#
# Description: Mimeapp script for adding torrent to transmission-daemon, but will also start
# the daemon first if not running
# Dependencies: notify-send, transmission

pgrep -x transmission-daemon > /dev/null || (transmission-daemon && notify-send "Starting transmission daemon...")
transmission-remote -a "$@" && notify-send "Transmission-daemon" "Torrent added."
