#!/bin/sh
#
# Description: Send a push notification when transmission-daemon has finished downloading a torrent
# Dependencies: notify-send, transmission
#
# The following is a list of exports which are set by transmission-daemon:
# - TR_APP_VERSION
# - TR_TIME_LOCALTIME
# - TR_TORRENT_DIR
# - TR_TORRENT_HASH
# - TR_TORRENT_ID
# - TR_TORRENT_NAME

notify-send "Transmission-daemon" "$TR_TORRENT_NAME has finished downloading."
